# Generated by Django 5.0.4 on 2024-04-14 05:40

import countia.managers
import countia.models
import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INC', 'Increase'), ('DEC', 'Decrease')], default='DEC', max_length=3)),
                ('currency', models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'Euro'), ('CNY', 'Yuan'), ('JPY', 'Yen'), ('GBP', 'Pound')], default='USD', max_length=3)),
                ('time', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('amount', models.FloatField()),
                ('description', models.CharField(blank=True, null=True, verbose_name='description')),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', countia.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'Euro'), ('CNY', 'Yuan'), ('JPY', 'Yen'), ('GBP', 'Pound')], default='USD', max_length=3)),
                ('amount', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='category')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='countia.category')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringRecord',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='countia.record')),
                ('is_infinite', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('repetition_dates', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('end_date', models.TimeField(default=countia.models.one_month_from_now)),
            ],
            bases=('countia.record',),
        ),
        migrations.AddField(
            model_name='record',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='record',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='countia.category'),
        ),
    ]
